version: '3'
services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd nextjs-on-docker && npm run dev"
    ports:
      - "3000:3000"
  storybook:
    build:
      context: .
    command: sh -c "cd nextjs-on-docker && npm run storybook"
    ports:
      - "6006:6006"
    volumes:
      - ./:/usr/src/app
